### ISSUE TITLE
Small follow-up actions from code reviews

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#40]
This meta-issue will track various small follow-up actions from code review iterations.

- [x] https://github.com/EBIvariation/trait-curation/pull/35#discussion_r440161830 Reformat two lines into a single line
- [x] https://github.com/EBIvariation/trait-curation/pull/35#discussion_r441881504 Avoid code duplication in the list of statuses by moving some of them into a variable
- [x] https://github.com/EBIvariation/trait-curation/pull/35#discussion_r440158511 Use rem units globally in the CSS

**Comment by tskir** [comment]
They've been fixed by #45 so I'm going to close this issue. If we have small follow-up actions in the future, we can create new issues
